name: Java CI with Maven

on:
  push:
    branches: 
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      run: mvn -B test --file Server/Auth/pom.xml
